{{- if .Values.auditLogsPersistence.enabled -}}
{{- if not .Values.auditLogsPersistence.existingClaim -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "auditmanager.auditLogsPvcName" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    {{- range .Values.auditLogsPersistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.auditLogsPersistence.size | quote }}
  {{- if .Values.auditLogsPersistence.storageClass }}
  {{- if (eq "-" .Values.auditLogsPersistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.auditLogsPersistence.storageClass }}"
  {{- end }}
  {{- end }}
{{- end -}}
{{- end -}}
